name: Pipeline for Maven

on:
  push:
    branches: ["feature/3-undo-redo"]
  pull_request:
    branches: ["feature/3-undo-redo"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven
      - name: Install and run Xvfb (display server)
        run: |
          sudo apt update
          sudo apt install xvfb -y
          Xvfb :99 -screen 0 1024x768x24 &
          export DISPLAY=:99
      - name: Maven compile and test
        env:
          USER_NAME: ${{ github.actor }}
          TOKEN: ${{ github.token }}
          DISPLAY: :99
        run: mvn clean compile -Dmaven.compiler.showWarnings=false
